[package]
name = "v3"
version = "0.1.0"
edition = "2021"
repository = ""
authors = ["Bax"]
readme = "README.md"
license = ""
description = """
A datatype library that allows for measurement unit association, conversion, and operations for values.
"""

[lib]
name = "v3"
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "v3bench"
harness = false